Sprint 3
OBeliakov/react-burger pull request #5
Opened 2023-04-06 22:57 UTC by OBeliakov

2023-04-07 05:20 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец!**

- Сборка и запуск проекта выполняются без ошибок;
- Теперь у вас есть роутинг;
- Есть регистрация и авторизация;

### **Но есть несколько замечаний, которые нужно исправить:**

- <https://disk.yandex.com/i/SaVQ-uYFTsebrQ> - Нужно исправить ошибку в консоли, она возникает если пытаешься перейти в `/register` (по кнопке зарегистрироваться);

- Вы должны добавлять в хедер запроса `POST /orders`, токен пользователя `Bearer ...`, чтобы сервер понимал что заказ сделал зарегистрированный пользователь (время обработки заказа должно быть в разы больше, если вы всё правильно сделали);

- По чек-листу, требуется реализовать:

  - При клике на «История заказов» происходит переход на экран `/profile/orders`, ссылка «История заказов» становится активной, экран `/profile/orders` пока отображается пустым. <https://disk.yandex.com/i/YwabJGOmS3nksA> - вкладка становится активной и меняется надпись, контентную область пока оставить пустой;

- Следует разделить экшены по файлам, на нас есть несколько задач (доменных областей) не связанных между собой - загрузка ингредиентов, оформление заказа, работа конструктор. Лучше, что бы экшены относящиеся к решению каждой были описаны в своем файле, т.к. приложение со времени будет развиваться, будет добавлять новый функционал и плохо, если придется все экшены описывать в одном файле, он будет слишком большой.

- Cо временем приложение будет разрастаться, появится новый функционал, если все будет в одном редьюсере он станет слишком большим, разделите один большой редьюсер на несколько, обрабатывающие данные одной предметной области (одного "домена"), Для объединения редьюсеров используйте combineReducers.

### **Сделает код лучше:**

- url такого типа, лучше выносить за пределы компонента;

  ```js
    const _registerUrl =`${\_apiBase}/auth/register`;
  ```

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: <https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders>

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**

2023-04-07 05:20 UTC, ArslanDev666 commented on src/components/services/utils.js
> +};
**Надо исправить:**

функция `checkResponse` должна просто проверять запрос, она не должна знать о диспатчах, или делать какие-то другие действия.
Какие-то действия вы можете делать дальше по цепочке в `.then`;

2023-04-07 05:20 UTC, ArslanDev666 commented on src/components/services/constants.js
> +export const _apiBase = "https://norma.nomoreparties.space/api";
**Надо исправить:**

имена констант принято записывать в стиле UPPER_CASE

2023-04-07 05:20 UTC, ArslanDev666 commented on src/components/services/actions/actions.js
> +            "https://norma.nomoreparties.space/api/auth/user",
**Надо исправить:**

вынести адрес сервера в файл консатант. или использовать `url`.

2023-04-07 05:20 UTC, ArslanDev666 commented on src/pages/registration/registration.jsx
> +    });
Кажется, тут должно быть что-то ещё, а то не очень логично просто так перенаправлять пользователя с этой страницы, на главную.

2023-04-08 09:18 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец! Работа принята, удачи в дальнейшем обучении!**

- Всё круто 🔥, все замечания были исправлены;

2023-04-08 09:26 UTC, OBeliakov commented
@ArslanDev666 , спасибо за ревью и дельные советы!

2023-04-08 09:27 UTC, merged